let x = [{
    "_readableState": {
        "objectMode": false,
        "highWaterMark": 16384,
        "buffer": {
            "head": "$[0].statusCode",
            "tail": "$[0].statusCode",
            "length": 0
        },
        "length": 0,
        "pipes": "$[0].statusCode",
        "pipesCount": 0,
        "flowing": "$[0].statusCode",
        "ended": true,
        "endEmitted": false,
        "reading": false,
        "sync": true,
        "needReadable": false,
        "emittedReadable": false,
        "readableListening": false,
        "resumeScheduled": false,
        "paused": true,
        "emitClose": true,
        "autoDestroy": false,
        "destroyed": false,
        "defaultEncoding": "utf8",
        "awaitDrain": 0,
        "readingMore": true,
        "decoder": "$[0].statusCode",
        "encoding": "$[0].statusCode"
    },
    "readable": true,
    "_events": {},
    "_eventsCount": 1,
    "socket": {
        "connecting": false,
        "_hadError": false,
        "_parent": "$[0].statusCode",
        "_host": "$[0].statusCode",
        "_readableState": {
            "objectMode": false,
            "highWaterMark": 16384,
            "buffer": {
                "head": "$[0].statusCode",
                "tail": "$[0].statusCode",
                "length": 0
            },
            "length": 0,
            "pipes": "$[0].statusCode",
            "pipesCount": 0,
            "flowing": true,
            "ended": false,
            "endEmitted": false,
            "reading": true,
            "sync": false,
            "needReadable": true,
            "emittedReadable": false,
            "readableListening": false,
            "resumeScheduled": false,
            "paused": false,
            "emitClose": false,
            "autoDestroy": false,
            "destroyed": false,
            "defaultEncoding": "utf8",
            "awaitDrain": 0,
            "readingMore": false,
            "decoder": "$[0].statusCode",
            "encoding": "$[0].statusCode"
        },
        "readable": true,
        "_events": {
            "end": [null, null],
            "drain": [null, null],
            "close": [null, null]
        },
        "_eventsCount": 8,
        "_writableState": {
            "objectMode": false,
            "highWaterMark": 16384,
            "finalCalled": false,
            "needDrain": false,
            "ending": false,
            "ended": false,
            "finished": false,
            "destroyed": false,
            "decodeStrings": false,
            "defaultEncoding": "utf8",
            "length": 0,
            "writing": false,
            "corked": 0,
            "sync": false,
            "bufferProcessing": false,
            "writecb": "$[0].statusCode",
            "writelen": 0,
            "bufferedRequest": "$[0].statusCode",
            "lastBufferedRequest": "$[0].statusCode",
            "pendingcb": 0,
            "prefinished": false,
            "errorEmitted": false,
            "emitClose": false,
            "autoDestroy": false,
            "bufferedRequestCount": 0,
            "corkedRequestsFree": {
                "next": {
                    "next": "$[0].statusCode",
                    "entry": "$[0].statusCode"
                },
                "entry": "$[0].statusCode"
            }
        },
        "writable": true,
        "allowHalfOpen": true,
        "_sockname": "$[0].statusCode",
        "_pendingData": "$[0].statusCode",
        "_pendingEncoding": "",
        "server": {
            "_events": {},
            "_eventsCount": 2,
            "_connections": 2,
            "_handle": {
                "reading": false
            },
            "_usingWorkers": false,
            "_workers": [],
            "_unref": false,
            "allowHalfOpen": true,
            "pauseOnConnect": false,
            "httpAllowHalfOpen": false,
            "timeout": 120000,
            "keepAliveTimeout": 5000,
            "maxHeadersCount": "$[0].statusCode",
            "headersTimeout": 40000,
            "_connectionKey": "4:0.0.0.0:3004"
        },
        "_server": "$[0].socket.server",
        "timeout": 120000,
        "parser": {
            "_headers": [],
            "_url": "",
            "socket": "$[0].socket",
            "incoming": "$[0]",
            "outgoing": "$[0].statusCode",
            "maxHeaderPairs": 2000,
            "_consumed": true,
            "parsingHeadersStart": 0
        },
        "_paused": false,
        "_httpMessage": {
            "_events": {},
            "_eventsCount": 2,
            "outputData": [],
            "outputSize": 0,
            "writable": true,
            "_last": false,
            "chunkedEncoding": true,
            "shouldKeepAlive": true,
            "useChunkedEncodingByDefault": true,
            "sendDate": true,
            "_removedConnection": false,
            "_removedContLen": false,
            "_removedTE": false,
            "_contentLength": "$[0].statusCode",
            "_hasBody": true,
            "_trailer": "",
            "finished": false,
            "_headerSent": true,
            "socket": "$[0].socket",
            "connection": "$[0].socket",
            "_header": "HTTP/1.1 200 OK\r\nContent-Type: text/event-stream\r\nCache-Control: no-cache, no-transform\r\nConnection: keep-alive\r\nDate: Sun, 07 Jul 2019 11:22:11 GMT\r\nTransfer-Encoding: chunked\r\n\r\n",
            "_sent100": false,
            "_expect_continue": false,
            "statusMessage": "OK",
            "statusCode": 200
        }
    },
    "connection": "$[0].socket",
    "httpVersionMajor": 1,
    "httpVersionMinor": 1,
    "httpVersion": "1.1",
    "complete": true,
    "headers": {
        "host": "localhost:3004",
        "connection": "keep-alive",
        "accept": "text/event-stream",
        "cache-control": "no-cache",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36",
        "referer": "http://localhost:3004/",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "hu-HU,hu;q=0.9,en-US;q=0.8,en;q=0.7,lv;q=0.6",
        "cookie": "name=tobi; /1/cica=1; adonis-session=a9d639c6827392557c1ae820944d7e5fgr%2FS89K43BxfZmpKVGxifDmVFhkfIgBmo1%2FhjwH3V9kBrWl0HOtT%2FGZq6ukkBXsVjAIp6TvLyFt3Fkgb4ORASDxFG%2BF5aN0Xq4DX8O1pn0SgJJYRtZ%2BfJUlWM3KBImob; adonis-session-values=5ffde79113073e0c15d40e0e9b2aa098H2zwCtdFiQ6L4MO5BjHTZEqhhiPXP4WSPqt%2F5YehCX4cIHHjAuDS%2BhwMYxbIgfNW%2F4%2FZZHvxzXz%2BgxY3qCGAwjZ2IvO6W%2FHlla%2FrZIL9syCGf9uELJgEO5OP2N%2B9GoqNsLgd3D5XCISZJ%2BQUMLrx7chbcprx3PesLjBbv02Lq94%3D"
    },
    "rawHeaders": ["Host", "localhost:3004", "Connection", "keep-alive", "Accept", "text/event-stream", "Cache-Control", "no-cache", "User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36", "Referer", "http://localhost:3004/", "Accept-Encoding", "gzip, deflate, br", "Accept-Language", "hu-HU,hu;q=0.9,en-US;q=0.8,en;q=0.7,lv;q=0.6", "Cookie", "name=tobi; /1/cica=1; adonis-session=a9d639c6827392557c1ae820944d7e5fgr%2FS89K43BxfZmpKVGxifDmVFhkfIgBmo1%2FhjwH3V9kBrWl0HOtT%2FGZq6ukkBXsVjAIp6TvLyFt3Fkgb4ORASDxFG%2BF5aN0Xq4DX8O1pn0SgJJYRtZ%2BfJUlWM3KBImob; adonis-session-values=5ffde79113073e0c15d40e0e9b2aa098H2zwCtdFiQ6L4MO5BjHTZEqhhiPXP4WSPqt%2F5YehCX4cIHHjAuDS%2BhwMYxbIgfNW%2F4%2FZZHvxzXz%2BgxY3qCGAwjZ2IvO6W%2FHlla%2FrZIL9syCGf9uELJgEO5OP2N%2B9GoqNsLgd3D5XCISZJ%2BQUMLrx7chbcprx3PesLjBbv02Lq94%3D"],
    "trailers": {},
    "rawTrailers": [],
    "aborted": false,
    "upgrade": false,
    "url": "/sse",
    "method": "GET",
    "statusCode": null,
    "statusMessage": "$[0].statusCode",
    "client": "$[0].socket",
    "_consuming": false,
    "_dumped": false
}];